name: Workflow / Lint

on:
  push:
    paths:
      - "**.py"
      - requirements.txt
  pull_request:
    paths:
      - "**.py"
      - requirements.txt

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 📦 Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: ⚙️ Lint
        run: python3 -m ruff check .

      - name: 💅 Format
        run: python3 -m ruff format . --check
